# -*- coding: utf-8 -*-
"""DSE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ah1UisXAFvPqWM9Fgf5N_7Z-y_o0fDy-
"""



import requests
from bs4 import BeautifulSoup
import os
from datetime import datetime
from openpyxl import load_workbook, Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ── Config ────────────────────────────────────────────────────────────────────
EXCEL_FILE = "dse_stocks.xlsx"
URL        = "https://www.dsebd.org/latest_share_price_scroll_group.php"

# ── Styles ────────────────────────────────────────────────────────────────────
HEADER_FILL = PatternFill("solid", start_color="006B6B")
HEADER_FONT = Font(bold=True, color="FFFFFF", name="Arial", size=10)
ALT_FILL    = PatternFill("solid", start_color="F2FAFA")
UP_FILL     = PatternFill("solid", start_color="E6F9EC")
DOWN_FILL   = PatternFill("solid", start_color="FDE8E8")
UP_FONT     = Font(name="Arial", size=10, color="1A7A1A", bold=True)
DOWN_FONT   = Font(name="Arial", size=10, color="CC0000", bold=True)
NORMAL_FONT = Font(name="Arial", size=10)
BORDER = Border(
    left=Side(style="thin",   color="CCCCCC"),
    right=Side(style="thin",  color="CCCCCC"),
    top=Side(style="thin",    color="CCCCCC"),
    bottom=Side(style="thin", color="CCCCCC"),
)

DATA_COLS  = ["DATE", "#", "TRADING CODE", "LTP*", "HIGH", "LOW",
              "CLOSEP*", "YCP*", "CHANGE", "TRADE", "VALUE (mn)", "VOLUME"]
COL_WIDTHS = [12, 5, 16, 9, 9, 9, 10, 9, 9, 9, 12, 14]

# ── Session ───────────────────────────────────────────────────────────────────
session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0",
    "Accept-Language": "en-US,en;q=0.9"
})

# ── FIXED FETCH FUNCTION (IMPORTANT) ──────────────────────────────────────────
def fetch_group(group="A"):
    resp = session.get(URL, params={"group": group}, timeout=15)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")

    rows = []

    # 🔥 Key fix: use a.ab1 (one per stock)
    for a_tag in soup.select("a.ab1"):
        tr = a_tag.find_parent("tr")
        if not tr:
            continue

        tds = tr.find_all("td")
        if len(tds) < 11:
            continue

        code = a_tag.get_text(strip=True)

        rows.append({
            "#":           tds[0].get_text(strip=True),
            "TRADING CODE": code,
            "LTP*":        tds[2].get_text(strip=True),
            "HIGH":        tds[3].get_text(strip=True),
            "LOW":         tds[4].get_text(strip=True),
            "CLOSEP*":     tds[5].get_text(strip=True),
            "YCP*":        tds[6].get_text(strip=True),
            "CHANGE":      tds[7].get_text(strip=True),
            "TRADE":       tds[8].get_text(strip=True),
            "VALUE (mn)":  tds[9].get_text(strip=True),
            "VOLUME":      tds[10].get_text(strip=True),
        })

    return rows

# ── Excel helpers ─────────────────────────────────────────────────────────────
def style_header(ws):
    for col_idx, (col, width) in enumerate(zip(DATA_COLS, COL_WIDTHS), 1):
        cell           = ws.cell(row=1, column=col_idx)
        cell.value     = col
        cell.font      = HEADER_FONT
        cell.fill      = HEADER_FILL
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.border    = BORDER
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    ws.freeze_panes = "A2"

def style_data_row(ws, row_num, change_val):
    try:
        change = float(str(change_val).replace(",", ""))
    except:
        change = 0

    if change > 0:
        fill, font = UP_FILL, UP_FONT
    elif change < 0:
        fill, font = DOWN_FILL, DOWN_FONT
    else:
        fill, font = None, NORMAL_FONT

    for col_idx in range(1, len(DATA_COLS) + 1):
        cell = ws.cell(row=row_num, column=col_idx)
        cell.font = font
        cell.border = BORDER
        cell.alignment = Alignment(horizontal="center", vertical="center")

        if fill:
            cell.fill = fill
        elif row_num % 2 == 0:
            cell.fill = ALT_FILL

def get_or_create_sheet(wb, name):
    safe = name[:31]
    if safe in wb.sheetnames:
        return wb[safe], False
    ws = wb.create_sheet(title=safe)
    style_header(ws)
    return ws, True

def row_is_duplicate(ws, row_dict):
    if ws.max_row < 2:
        return False

    compare_cols = list(range(4, len(DATA_COLS) + 1))

    new_vals = [str(row_dict.get(DATA_COLS[c - 1], "")).strip() for c in compare_cols]
    last_vals = [str(ws.cell(row=ws.max_row, column=c).value or "").strip() for c in compare_cols]

    return new_vals == last_vals

# ── Main ──────────────────────────────────────────────────────────────────────
def run(groups=("A","B","G","N","Z")):
    wb = load_workbook(EXCEL_FILE) if os.path.isfile(EXCEL_FILE) else Workbook()

    if "Sheet" in wb.sheetnames:
        wb.remove(wb["Sheet"])

    today = datetime.now().strftime("%Y-%m-%d")

    for group in groups:
        print(f"\nGroup {group}")

        stocks = fetch_group(group)

        for stock in stocks:
            code = stock.get("TRADING CODE","").strip()
            if not code:
                continue

            ws, is_new = get_or_create_sheet(wb, code)

            if not is_new and row_is_duplicate(ws, stock):
                print(f"= {code} (duplicate)")
                continue

            row = [today] + [stock.get(c,"") for c in DATA_COLS[1:]]
            ws.append(row)
            style_data_row(ws, ws.max_row, stock.get("CHANGE",0))

            if is_new:
                print(f"✚ {code}")
            else:
                print(f"↑ {code}")

    wb.save(EXCEL_FILE)
    print("\nDONE → saved to", EXCEL_FILE)

# ── Run ───────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    run(groups=("A","B","G","N","Z"))

# at the end of script.py
from datetime import datetime

with open("last_run.txt", "w") as f:
    f.write(datetime.now().strftime("%Y-%m-%d"))
