# -*- coding: utf-8 -*-
"""DSE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ah1UisXAFvPqWM9Fgf5N_7Z-y_o0fDy-
"""



import requests
from bs4 import BeautifulSoup
import os
from datetime import datetime
from openpyxl import load_workbook, Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ── Config ────────────────────────────────────────────────────────────────────
EXCEL_FILE = "dse_stocks.xlsx"
URL        = "https://www.dsebd.org/latest_share_price_scroll_group.php"

# ── Styles ────────────────────────────────────────────────────────────────────
HEADER_FILL = PatternFill("solid", start_color="006B6B")
HEADER_FONT = Font(bold=True, color="FFFFFF", name="Arial", size=10)
ALT_FILL    = PatternFill("solid", start_color="F2FAFA")
UP_FILL     = PatternFill("solid", start_color="E6F9EC")
DOWN_FILL   = PatternFill("solid", start_color="FDE8E8")
UP_FONT     = Font(name="Arial", size=10, color="1A7A1A", bold=True)
DOWN_FONT   = Font(name="Arial", size=10, color="CC0000", bold=True)
NORMAL_FONT = Font(name="Arial", size=10)
BORDER = Border(
    left=Side(style="thin",   color="CCCCCC"),
    right=Side(style="thin",  color="CCCCCC"),
    top=Side(style="thin",    color="CCCCCC"),
    bottom=Side(style="thin", color="CCCCCC"),
)

# GROUP column is injected at runtime (not from the scraped row)
DATA_COLS  = ["DATE", "#", "TRADING CODE", "GROUP", "LTP*", "HIGH", "LOW",
              "CLOSEP*", "YCP*", "CHANGE", "TRADE", "VALUE (mn)", "VOLUME"]
COL_WIDTHS = [12,      5,   16,            7,        9,      9,      9,
              10,       9,    9,        9,       12,          14]

# ── Session ───────────────────────────────────────────────────────────────────
session = requests.Session()
session.headers.update({
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
    "Cache-Control": "max-age=0",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                   "AppleWebKit/537.36 (KHTML, like Gecko) "
                   "Chrome/146.0.0.0 Safari/537.36"),
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-User": "?1",
    "sec-ch-ua": '"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
})
session.cookies.update({
    "PHPSESSID": "osp4v42e6rk2i5v080df4rr0a0",   # refresh from browser if expired
})

# ── Fetch ─────────────────────────────────────────────────────────────────────
def fetch_group(group="A"):
    """
    Scrape one group page using <a class="ab1"> to locate every stock row.
    Returns a list of dicts. GROUP is NOT included here — it's added in run().
    """
    resp = session.get(URL, params={"group": group}, timeout=15)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")

    rows = []
    for a_tag in soup.select("a.ab1"):
        tr = a_tag.find_parent("tr")
        if not tr:
            continue
        tds = tr.find_all("td")
        if len(tds) < 11:
            continue
        rows.append({
            "#":            tds[0].get_text(strip=True),
            "TRADING CODE": a_tag.get_text(strip=True),   # clean code from <a>
            "LTP*":         tds[2].get_text(strip=True),
            "HIGH":         tds[3].get_text(strip=True),
            "LOW":          tds[4].get_text(strip=True),
            "CLOSEP*":      tds[5].get_text(strip=True),
            "YCP*":         tds[6].get_text(strip=True),
            "CHANGE":       tds[7].get_text(strip=True),
            "TRADE":        tds[8].get_text(strip=True),
            "VALUE (mn)":   tds[9].get_text(strip=True),
            "VOLUME":       tds[10].get_text(strip=True),
        })
    return rows

# ── Excel helpers ─────────────────────────────────────────────────────────────
def style_header(ws):
    for col_idx, (col, width) in enumerate(zip(DATA_COLS, COL_WIDTHS), 1):
        cell           = ws.cell(row=1, column=col_idx)
        cell.value     = col
        cell.font      = HEADER_FONT
        cell.fill      = HEADER_FILL
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border    = BORDER
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    ws.row_dimensions[1].height = 32
    ws.freeze_panes = "A2"

def style_data_row(ws, row_num, change_val):
    try:
        change = float(str(change_val).replace(",", ""))
    except:
        change = 0
    if change > 0:
        fill, font = UP_FILL, UP_FONT
    elif change < 0:
        fill, font = DOWN_FILL, DOWN_FONT
    else:
        fill, font = None, NORMAL_FONT
    for col_idx in range(1, len(DATA_COLS) + 1):
        cell           = ws.cell(row=row_num, column=col_idx)
        cell.font      = font
        cell.border    = BORDER
        cell.alignment = Alignment(horizontal="center", vertical="center")
        if fill:
            cell.fill = fill
        elif row_num % 2 == 0:
            cell.fill = ALT_FILL

def get_or_create_sheet(wb, name):
    safe = name[:31]           # Excel sheet name limit
    if safe in wb.sheetnames:
        return wb[safe], False
    ws = wb.create_sheet(title=safe)
    style_header(ws)
    return ws, True

def row_is_duplicate(ws, stock, group):
    """Compare price fields of the new row against the last saved row."""
    if ws.max_row < 2:
        return False
    # Build the full ordered row (same as what we append) then compare cols 4+
    full_new = build_row("__check__", stock, group)
    compare_cols = list(range(4, len(DATA_COLS) + 1))   # GROUP … VOLUME
    new_vals  = [str(full_new[c - 1]).strip() for c in compare_cols]
    last_vals = [str(ws.cell(row=ws.max_row, column=c).value or "").strip() for c in compare_cols]
    return new_vals == last_vals

def build_row(today, stock, group):
    """
    Assemble one Excel row in DATA_COLS order:
      DATE | # | TRADING CODE | GROUP | LTP* | HIGH | LOW |
      CLOSEP* | YCP* | CHANGE | TRADE | VALUE (mn) | VOLUME
    """
    return [
        today,
        stock.get("#", ""),
        stock.get("TRADING CODE", ""),
        group,                          # injected from the loop
        stock.get("LTP*", ""),
        stock.get("HIGH", ""),
        stock.get("LOW", ""),
        stock.get("CLOSEP*", ""),
        stock.get("YCP*", ""),
        stock.get("CHANGE", ""),
        stock.get("TRADE", ""),
        stock.get("VALUE (mn)", ""),
        stock.get("VOLUME", ""),
    ]

# ── Main ──────────────────────────────────────────────────────────────────────
def run(groups=("A", "B", "G", "N", "Z")):
    wb = load_workbook(EXCEL_FILE) if os.path.isfile(EXCEL_FILE) else Workbook()
    for default in ("Sheet", "Sheet1"):
        if default in wb.sheetnames and len(wb.sheetnames) > 1:
            wb.remove(wb[default])

    today = datetime.now().strftime("%Y-%m-%d")
    created = appended = duplicate = errors = 0

    for group in groups:
        print(f"\n── Group {group} {'─'*35}")
        try:
            stocks = fetch_group(group)
        except Exception as e:
            print(f"  ✗ Failed: {e}")
            errors += 1
            continue

        if not stocks:
            print("  ⚠ No rows found (market closed or session expired?)")
            continue

        for stock in stocks:
            code = stock.get("TRADING CODE", "").strip()
            if not code:
                continue
            try:
                ws, is_new = get_or_create_sheet(wb, code)

                if not is_new and row_is_duplicate(ws, stock, group):
                    print(f"  =  {code:<18} (duplicate – skipped)")
                    duplicate += 1
                    continue

                ws.append(build_row(today, stock, group))
                style_data_row(ws, ws.max_row, stock.get("CHANGE", 0))

                if is_new or ws.max_row == 2:
                    print(f"  ✚  {code:<18} (new sheet)")
                    created += 1
                else:
                    print(f"  ↑  {code:<18} (appended)")
                    appended += 1

            except Exception as e:
                print(f"  ✗  {code}: {e}")
                errors += 1

    wb.save(EXCEL_FILE)
    print(f"\n{'═'*45}")
    print(f"  ✚ New sheets : {created}")
    print(f"  ↑ Appended   : {appended}")
    print(f"  = Duplicate  : {duplicate}")
    print(f"  ✗ Errors     : {errors}")
    print(f"  Saved  →  {EXCEL_FILE}")
    print(f"{'═'*45}\n")

if __name__ == "__main__":
    run(groups=("A", "B", "G", "N", "Z"))

# at the end of script.py
from datetime import datetime

with open("last_run.txt", "w") as f:
    f.write(datetime.now().strftime("%Y-%m-%d"))
